---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: present

- name: Install Python 3.8
  yum:
    name: 
      - python38
      - python38-pip
    state: present

- name: Set Python 3.8 as default python3
  alternatives:
    name: python3
    path: /usr/bin/python3.8
    link: /usr/bin/python3