---
- name: Create app directory
  file:
    path: /app
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Copy Docker image
  copy:
    src: app.tar
    dest: /app/app.tar

- name: Load Docker image
  docker_image:
    name: allowance-checker
    load_path: /app/app.tar
    source: load

- name: Run application container
  docker_container:
    name: app
    image: allowance-checker
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
    env:
      VITE_APIKEY: "{{ vite_apikey }}"